// Code generated by entc, DO NOT EDIT.

package flowdeployment

const (
	// Label holds the string label denoting the flowdeployment type in the database.
	Label = "flow_deployment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldFlowDefinitionID holds the string denoting the flow_definition_id field in the database.
	FieldFlowDefinitionID = "flow_definition_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgeFlowDefinition holds the string denoting the flow_definition edge name in mutations.
	EdgeFlowDefinition = "flow_definition"
	// EdgeFlowInstances holds the string denoting the flow_instances edge name in mutations.
	EdgeFlowInstances = "flow_instances"
	// Table holds the table name of the flowdeployment in the database.
	Table = "flow_deployments"
	// FlowDefinitionTable is the table that holds the flow_definition relation/edge.
	FlowDefinitionTable = "flow_deployments"
	// FlowDefinitionInverseTable is the table name for the FlowDefinition entity.
	// It exists in this package in order to avoid circular dependency with the "flowdefinition" package.
	FlowDefinitionInverseTable = "flow_definitions"
	// FlowDefinitionColumn is the table column denoting the flow_definition relation/edge.
	FlowDefinitionColumn = "flow_definition_id"
	// FlowInstancesTable is the table that holds the flow_instances relation/edge.
	FlowInstancesTable = "flow_instances"
	// FlowInstancesInverseTable is the table name for the FlowInstance entity.
	// It exists in this package in order to avoid circular dependency with the "flowinstance" package.
	FlowInstancesInverseTable = "flow_instances"
	// FlowInstancesColumn is the table column denoting the flow_instances relation/edge.
	FlowInstancesColumn = "flow_deployment_id"
)

// Columns holds all SQL columns for flowdeployment fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldFlowDefinitionID,
	FieldName,
	FieldStatus,
	FieldModel,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() int64
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() int64
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int64
	// FlowDefinitionIDValidator is a validator for the "flow_definition_id" field. It is called by the builders before save.
	FlowDefinitionIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
	// DefaultRemark holds the default value on creation for the "remark" field.
	DefaultRemark string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)
