// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/BeanWei/li/li-engine/contrib/liflow/ent/runtime.go

const (
	Version = "v0.10.2-0.20220408082730-6e4e4da89674"           // Version of ent codegen.
	Sum     = "h1:YMUBe+itzJQhVTkrV3sRzoX7EwUVwQc5ZQ+oXxIsQIg=" // Sum of ent codegen.
)
