import {
  Action,
  ArrayBase,
  ArrayItems,
  ArrayTable,
  Avatar,
  CardItem,
  Cascader,
  Checkbox,
  ColorSelect,
  DatePicker,
  Divider,
  DropdownMenu,
  Form,
  FormButtonGroup,
  FormGrid,
  FormItem,
  FormLayout,
  Grid,
  Input,
  InputNumber,
  List,
  Menu,
  Money,
  Password,
  Radio,
  Reset,
  Select,
  Space,
  Submit,
  Switch,
  TimePicker,
  Upload,
} from "../components";
import { SchemaComponentOptions } from "./SchemaComponentOptions";

export const UiSchemaComponentProvider = (props: any) => {
  const { children } = props;
  return (
    <SchemaComponentOptions
      components={{
        Action,
        ArrayBase,
        ArrayItems,
        ArrayTable,
        Avatar,
        CardItem,
        Cascader,
        Checkbox,
        ColorSelect,
        DatePicker,
        Divider,
        DropdownMenu,
        Form,
        FormButtonGroup,
        FormGrid,
        FormItem,
        FormLayout,
        Grid,
        Input,
        InputNumber,
        List,
        Menu,
        Money,
        Password,
        Radio,
        Reset,
        Select,
        Space,
        Submit,
        Switch,
        TimePicker,
        Upload,
      }}
    >
      {children}
    </SchemaComponentOptions>
  );
};
