package liflow

import "github.com/gogf/gf/v2/errors/gcode"

var (
	// 流程定义错误
	ErrCodeFlowNotExists                 = gcode.New(9101, "Flow not exist", nil)
	ErrCodeFlowNotEditing                = gcode.New(9102, "Flow not editing status", nil)
	ErrCodeEmptyModel                    = gcode.New(9201, "Empty model", nil)
	ErrCodeStartNodeInvalid              = gcode.New(9202, "Zero or more than one start node", nil)
	ErrCodeElementKeyNotUnique           = gcode.New(9203, "Element key not unique", nil)
	ErrCodeEndNodeInvalid                = gcode.New(9204, "No end node", nil)
	ErrCodeModelNotUnicom                = gcode.New(9205, "Not unicom", nil)
	ErrCodeSequenceBelongToMultiPairNode = gcode.New(9206, "Sequence belong to multi pair node", nil)
	ErrCodeRingWrong                     = gcode.New(9207, "Ring wrong", nil)
	ErrCodeGatewayNoOutgoing             = gcode.New(9208, "Gateway no outgoing", nil)
	ErrCodeEmptySequenceOutgoing         = gcode.New(9209, "Empty sequence outgoing", nil)
	ErrCodeTooManyDefaultSequence        = gcode.New(9210, "Too many default sequence", nil)
	ErrCodeModelUnknownElementKey        = gcode.New(9211, "Unknown element key", nil)
	ErrCodeElementTooMuchIncoming        = gcode.New(9212, "Too many incoming", nil)
	ErrCodeElementTooMuchOutgoing        = gcode.New(9213, "Too many outgoing", nil)
	ErrCodeElementLackMuchIncoming       = gcode.New(9214, "Element lack incoming", nil)
	ErrCodeElementLackMuchOutgoing       = gcode.New(9215, "Element lack outgoing", nil)
	// 流程执行错误
	ErrCodeCommitFailed                  = gcode.New(9501, "Commit task failed", nil)
	ErrCodeRollbackFailed                = gcode.New(9502, "Rollback task failed", nil)
	ErrCodeCommitRejected                = gcode.New(9503, "Commit rejected, flow is terminate", nil)
	ErrCodeRollbackRejected              = gcode.New(9504, "Rollback rejected, non-running flowInstance to rollback", nil)
	ErrCodeNoNodeToRollback              = gcode.New(9505, "No node to rollback", nil)
	ErrCodeNodeUserTaskToRollback        = gcode.New(9506, "No userTask to rollback", nil)
	ErrCodeGetFlowDeploymentFailed       = gcode.New(9507, "Get flowDeployment failed", nil)
	ErrCodeGetFlowInstanceFailed         = gcode.New(9508, "Get flowInstance failed", nil)
	ErrCodeGetNodeFailed                 = gcode.New(9509, "Get current node failed", nil)
	ErrCodeGetNodeInstanceFailed         = gcode.New(9510, "Get nodeInstance failed", nil)
	ErrCodeGetInstanceDataFailed         = gcode.New(9511, "Get instanceData failed", nil)
	ErrCodeGetHookConfigFaield           = gcode.New(9512, "Get hook config failed", nil)
	ErrCodeGetOutgoingFailed             = gcode.New(9513, "Get outgoing failed", nil)
	ErrCodeUnsupportElementType          = gcode.New(9514, "Unsupported element type", nil)
	ErrCodeUnsupportElementFlowType      = gcode.New(9515, "Unsupported element flow type", nil)
	ErrCodeMissingData                   = gcode.New(9516, "Miss data", nil)
	ErrCodeSaveFlowInstanceFailed        = gcode.New(9517, "Save flowInstance failed", nil)
	ErrCodeSaveInstanceDataFailed        = gcode.New(9518, "Save instanceData failed", nil)
	ErrCodeSaveNodeInstanceListFailed    = gcode.New(9519, "Save nodeInstanceList failed", nil)
	ErrCodeSaveNodeInstanceLogListFailed = gcode.New(9520, "Save nodeInstanceLogList failed", nil)
	ErrCodeExpressionCalculateFailed     = gcode.New(9521, "Expression calculate failed", nil)
)
