// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BeanWei/li/li-engine/contrib/liflow/ent/flownodeinstance"
	"github.com/BeanWei/li/li-engine/contrib/liflow/ent/predicate"
)

// FlowNodeInstanceDelete is the builder for deleting a FlowNodeInstance entity.
type FlowNodeInstanceDelete struct {
	config
	hooks    []Hook
	mutation *FlowNodeInstanceMutation
}

// Where appends a list predicates to the FlowNodeInstanceDelete builder.
func (fnid *FlowNodeInstanceDelete) Where(ps ...predicate.FlowNodeInstance) *FlowNodeInstanceDelete {
	fnid.mutation.Where(ps...)
	return fnid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fnid *FlowNodeInstanceDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(fnid.hooks) == 0 {
		affected, err = fnid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FlowNodeInstanceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fnid.mutation = mutation
			affected, err = fnid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fnid.hooks) - 1; i >= 0; i-- {
			if fnid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fnid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fnid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (fnid *FlowNodeInstanceDelete) ExecX(ctx context.Context) int {
	n, err := fnid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fnid *FlowNodeInstanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: flownodeinstance.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: flownodeinstance.FieldID,
			},
		},
	}
	if ps := fnid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, fnid.driver, _spec)
}

// FlowNodeInstanceDeleteOne is the builder for deleting a single FlowNodeInstance entity.
type FlowNodeInstanceDeleteOne struct {
	fnid *FlowNodeInstanceDelete
}

// Exec executes the deletion query.
func (fnido *FlowNodeInstanceDeleteOne) Exec(ctx context.Context) error {
	n, err := fnido.fnid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{flownodeinstance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fnido *FlowNodeInstanceDeleteOne) ExecX(ctx context.Context) {
	fnido.fnid.ExecX(ctx)
}
