// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/BeanWei/li/li-engine/contrib/liflow/ent/flowdefinition"
	"github.com/BeanWei/li/li-engine/contrib/liflow/ent/flowdeployment"
	"github.com/BeanWei/li/li-engine/contrib/liflow/ent/flowinstance"
	"github.com/BeanWei/li/li-engine/contrib/liflow/ent/flowinstancedata"
	"github.com/BeanWei/li/li-engine/contrib/liflow/ent/flownodeinstance"
	"github.com/BeanWei/li/li-engine/contrib/liflow/ent/flownodeinstancelog"
	"github.com/BeanWei/li/li-engine/contrib/liflow/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	flowdefinitionMixin := schema.FlowDefinition{}.Mixin()
	flowdefinitionMixinFields0 := flowdefinitionMixin[0].Fields()
	_ = flowdefinitionMixinFields0
	flowdefinitionMixinFields1 := flowdefinitionMixin[1].Fields()
	_ = flowdefinitionMixinFields1
	flowdefinitionFields := schema.FlowDefinition{}.Fields()
	_ = flowdefinitionFields
	// flowdefinitionDescCreatedAt is the schema descriptor for created_at field.
	flowdefinitionDescCreatedAt := flowdefinitionMixinFields1[0].Descriptor()
	// flowdefinition.DefaultCreatedAt holds the default value on creation for the created_at field.
	flowdefinition.DefaultCreatedAt = flowdefinitionDescCreatedAt.Default.(func() int64)
	// flowdefinitionDescUpdatedAt is the schema descriptor for updated_at field.
	flowdefinitionDescUpdatedAt := flowdefinitionMixinFields1[1].Descriptor()
	// flowdefinition.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	flowdefinition.DefaultUpdatedAt = flowdefinitionDescUpdatedAt.Default.(func() int64)
	// flowdefinition.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	flowdefinition.UpdateDefaultUpdatedAt = flowdefinitionDescUpdatedAt.UpdateDefault.(func() int64)
	// flowdefinitionDescDeletedAt is the schema descriptor for deleted_at field.
	flowdefinitionDescDeletedAt := flowdefinitionMixinFields1[2].Descriptor()
	// flowdefinition.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	flowdefinition.DefaultDeletedAt = flowdefinitionDescDeletedAt.Default.(int64)
	// flowdefinitionDescName is the schema descriptor for name field.
	flowdefinitionDescName := flowdefinitionFields[0].Descriptor()
	// flowdefinition.NameValidator is a validator for the "name" field. It is called by the builders before save.
	flowdefinition.NameValidator = flowdefinitionDescName.Validators[0].(func(string) error)
	// flowdefinitionDescStatus is the schema descriptor for status field.
	flowdefinitionDescStatus := flowdefinitionFields[1].Descriptor()
	// flowdefinition.DefaultStatus holds the default value on creation for the status field.
	flowdefinition.DefaultStatus = flowdefinitionDescStatus.Default.(int8)
	// flowdefinitionDescRemark is the schema descriptor for remark field.
	flowdefinitionDescRemark := flowdefinitionFields[3].Descriptor()
	// flowdefinition.DefaultRemark holds the default value on creation for the remark field.
	flowdefinition.DefaultRemark = flowdefinitionDescRemark.Default.(string)
	// flowdefinitionDescID is the schema descriptor for id field.
	flowdefinitionDescID := flowdefinitionMixinFields0[0].Descriptor()
	// flowdefinition.DefaultID holds the default value on creation for the id field.
	flowdefinition.DefaultID = flowdefinitionDescID.Default.(func() string)
	// flowdefinition.IDValidator is a validator for the "id" field. It is called by the builders before save.
	flowdefinition.IDValidator = flowdefinitionDescID.Validators[0].(func(string) error)
	flowdeploymentMixin := schema.FlowDeployment{}.Mixin()
	flowdeploymentMixinFields0 := flowdeploymentMixin[0].Fields()
	_ = flowdeploymentMixinFields0
	flowdeploymentMixinFields1 := flowdeploymentMixin[1].Fields()
	_ = flowdeploymentMixinFields1
	flowdeploymentFields := schema.FlowDeployment{}.Fields()
	_ = flowdeploymentFields
	// flowdeploymentDescCreatedAt is the schema descriptor for created_at field.
	flowdeploymentDescCreatedAt := flowdeploymentMixinFields1[0].Descriptor()
	// flowdeployment.DefaultCreatedAt holds the default value on creation for the created_at field.
	flowdeployment.DefaultCreatedAt = flowdeploymentDescCreatedAt.Default.(func() int64)
	// flowdeploymentDescUpdatedAt is the schema descriptor for updated_at field.
	flowdeploymentDescUpdatedAt := flowdeploymentMixinFields1[1].Descriptor()
	// flowdeployment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	flowdeployment.DefaultUpdatedAt = flowdeploymentDescUpdatedAt.Default.(func() int64)
	// flowdeployment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	flowdeployment.UpdateDefaultUpdatedAt = flowdeploymentDescUpdatedAt.UpdateDefault.(func() int64)
	// flowdeploymentDescDeletedAt is the schema descriptor for deleted_at field.
	flowdeploymentDescDeletedAt := flowdeploymentMixinFields1[2].Descriptor()
	// flowdeployment.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	flowdeployment.DefaultDeletedAt = flowdeploymentDescDeletedAt.Default.(int64)
	// flowdeploymentDescFlowDefinitionID is the schema descriptor for flow_definition_id field.
	flowdeploymentDescFlowDefinitionID := flowdeploymentFields[0].Descriptor()
	// flowdeployment.FlowDefinitionIDValidator is a validator for the "flow_definition_id" field. It is called by the builders before save.
	flowdeployment.FlowDefinitionIDValidator = flowdeploymentDescFlowDefinitionID.Validators[0].(func(string) error)
	// flowdeploymentDescName is the schema descriptor for name field.
	flowdeploymentDescName := flowdeploymentFields[1].Descriptor()
	// flowdeployment.NameValidator is a validator for the "name" field. It is called by the builders before save.
	flowdeployment.NameValidator = flowdeploymentDescName.Validators[0].(func(string) error)
	// flowdeploymentDescStatus is the schema descriptor for status field.
	flowdeploymentDescStatus := flowdeploymentFields[2].Descriptor()
	// flowdeployment.DefaultStatus holds the default value on creation for the status field.
	flowdeployment.DefaultStatus = flowdeploymentDescStatus.Default.(int8)
	// flowdeploymentDescRemark is the schema descriptor for remark field.
	flowdeploymentDescRemark := flowdeploymentFields[4].Descriptor()
	// flowdeployment.DefaultRemark holds the default value on creation for the remark field.
	flowdeployment.DefaultRemark = flowdeploymentDescRemark.Default.(string)
	// flowdeploymentDescID is the schema descriptor for id field.
	flowdeploymentDescID := flowdeploymentMixinFields0[0].Descriptor()
	// flowdeployment.DefaultID holds the default value on creation for the id field.
	flowdeployment.DefaultID = flowdeploymentDescID.Default.(func() string)
	// flowdeployment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	flowdeployment.IDValidator = flowdeploymentDescID.Validators[0].(func(string) error)
	flowinstanceMixin := schema.FlowInstance{}.Mixin()
	flowinstanceMixinFields0 := flowinstanceMixin[0].Fields()
	_ = flowinstanceMixinFields0
	flowinstanceMixinFields1 := flowinstanceMixin[1].Fields()
	_ = flowinstanceMixinFields1
	flowinstanceFields := schema.FlowInstance{}.Fields()
	_ = flowinstanceFields
	// flowinstanceDescCreatedAt is the schema descriptor for created_at field.
	flowinstanceDescCreatedAt := flowinstanceMixinFields1[0].Descriptor()
	// flowinstance.DefaultCreatedAt holds the default value on creation for the created_at field.
	flowinstance.DefaultCreatedAt = flowinstanceDescCreatedAt.Default.(func() int64)
	// flowinstanceDescUpdatedAt is the schema descriptor for updated_at field.
	flowinstanceDescUpdatedAt := flowinstanceMixinFields1[1].Descriptor()
	// flowinstance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	flowinstance.DefaultUpdatedAt = flowinstanceDescUpdatedAt.Default.(func() int64)
	// flowinstance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	flowinstance.UpdateDefaultUpdatedAt = flowinstanceDescUpdatedAt.UpdateDefault.(func() int64)
	// flowinstanceDescDeletedAt is the schema descriptor for deleted_at field.
	flowinstanceDescDeletedAt := flowinstanceMixinFields1[2].Descriptor()
	// flowinstance.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	flowinstance.DefaultDeletedAt = flowinstanceDescDeletedAt.Default.(int64)
	// flowinstanceDescFlowDeploymentID is the schema descriptor for flow_deployment_id field.
	flowinstanceDescFlowDeploymentID := flowinstanceFields[0].Descriptor()
	// flowinstance.FlowDeploymentIDValidator is a validator for the "flow_deployment_id" field. It is called by the builders before save.
	flowinstance.FlowDeploymentIDValidator = flowinstanceDescFlowDeploymentID.Validators[0].(func(string) error)
	// flowinstanceDescRefID is the schema descriptor for ref_id field.
	flowinstanceDescRefID := flowinstanceFields[1].Descriptor()
	// flowinstance.RefIDValidator is a validator for the "ref_id" field. It is called by the builders before save.
	flowinstance.RefIDValidator = flowinstanceDescRefID.Validators[0].(func(string) error)
	// flowinstanceDescStatus is the schema descriptor for status field.
	flowinstanceDescStatus := flowinstanceFields[2].Descriptor()
	// flowinstance.DefaultStatus holds the default value on creation for the status field.
	flowinstance.DefaultStatus = flowinstanceDescStatus.Default.(int8)
	// flowinstanceDescID is the schema descriptor for id field.
	flowinstanceDescID := flowinstanceMixinFields0[0].Descriptor()
	// flowinstance.DefaultID holds the default value on creation for the id field.
	flowinstance.DefaultID = flowinstanceDescID.Default.(func() string)
	// flowinstance.IDValidator is a validator for the "id" field. It is called by the builders before save.
	flowinstance.IDValidator = flowinstanceDescID.Validators[0].(func(string) error)
	flowinstancedataMixin := schema.FlowInstanceData{}.Mixin()
	flowinstancedataMixinFields0 := flowinstancedataMixin[0].Fields()
	_ = flowinstancedataMixinFields0
	flowinstancedataMixinFields1 := flowinstancedataMixin[1].Fields()
	_ = flowinstancedataMixinFields1
	flowinstancedataFields := schema.FlowInstanceData{}.Fields()
	_ = flowinstancedataFields
	// flowinstancedataDescCreatedAt is the schema descriptor for created_at field.
	flowinstancedataDescCreatedAt := flowinstancedataMixinFields1[0].Descriptor()
	// flowinstancedata.DefaultCreatedAt holds the default value on creation for the created_at field.
	flowinstancedata.DefaultCreatedAt = flowinstancedataDescCreatedAt.Default.(func() int64)
	// flowinstancedataDescUpdatedAt is the schema descriptor for updated_at field.
	flowinstancedataDescUpdatedAt := flowinstancedataMixinFields1[1].Descriptor()
	// flowinstancedata.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	flowinstancedata.DefaultUpdatedAt = flowinstancedataDescUpdatedAt.Default.(func() int64)
	// flowinstancedata.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	flowinstancedata.UpdateDefaultUpdatedAt = flowinstancedataDescUpdatedAt.UpdateDefault.(func() int64)
	// flowinstancedataDescDeletedAt is the schema descriptor for deleted_at field.
	flowinstancedataDescDeletedAt := flowinstancedataMixinFields1[2].Descriptor()
	// flowinstancedata.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	flowinstancedata.DefaultDeletedAt = flowinstancedataDescDeletedAt.Default.(int64)
	// flowinstancedataDescFlowInstanceID is the schema descriptor for flow_instance_id field.
	flowinstancedataDescFlowInstanceID := flowinstancedataFields[0].Descriptor()
	// flowinstancedata.FlowInstanceIDValidator is a validator for the "flow_instance_id" field. It is called by the builders before save.
	flowinstancedata.FlowInstanceIDValidator = flowinstancedataDescFlowInstanceID.Validators[0].(func(string) error)
	// flowinstancedataDescType is the schema descriptor for type field.
	flowinstancedataDescType := flowinstancedataFields[4].Descriptor()
	// flowinstancedata.DefaultType holds the default value on creation for the type field.
	flowinstancedata.DefaultType = flowinstancedataDescType.Default.(int8)
	// flowinstancedataDescID is the schema descriptor for id field.
	flowinstancedataDescID := flowinstancedataMixinFields0[0].Descriptor()
	// flowinstancedata.DefaultID holds the default value on creation for the id field.
	flowinstancedata.DefaultID = flowinstancedataDescID.Default.(func() string)
	// flowinstancedata.IDValidator is a validator for the "id" field. It is called by the builders before save.
	flowinstancedata.IDValidator = flowinstancedataDescID.Validators[0].(func(string) error)
	flownodeinstanceMixin := schema.FlowNodeInstance{}.Mixin()
	flownodeinstanceMixinFields0 := flownodeinstanceMixin[0].Fields()
	_ = flownodeinstanceMixinFields0
	flownodeinstanceMixinFields1 := flownodeinstanceMixin[1].Fields()
	_ = flownodeinstanceMixinFields1
	flownodeinstanceFields := schema.FlowNodeInstance{}.Fields()
	_ = flownodeinstanceFields
	// flownodeinstanceDescCreatedAt is the schema descriptor for created_at field.
	flownodeinstanceDescCreatedAt := flownodeinstanceMixinFields1[0].Descriptor()
	// flownodeinstance.DefaultCreatedAt holds the default value on creation for the created_at field.
	flownodeinstance.DefaultCreatedAt = flownodeinstanceDescCreatedAt.Default.(func() int64)
	// flownodeinstanceDescUpdatedAt is the schema descriptor for updated_at field.
	flownodeinstanceDescUpdatedAt := flownodeinstanceMixinFields1[1].Descriptor()
	// flownodeinstance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	flownodeinstance.DefaultUpdatedAt = flownodeinstanceDescUpdatedAt.Default.(func() int64)
	// flownodeinstance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	flownodeinstance.UpdateDefaultUpdatedAt = flownodeinstanceDescUpdatedAt.UpdateDefault.(func() int64)
	// flownodeinstanceDescDeletedAt is the schema descriptor for deleted_at field.
	flownodeinstanceDescDeletedAt := flownodeinstanceMixinFields1[2].Descriptor()
	// flownodeinstance.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	flownodeinstance.DefaultDeletedAt = flownodeinstanceDescDeletedAt.Default.(int64)
	// flownodeinstanceDescFlowInstanceID is the schema descriptor for flow_instance_id field.
	flownodeinstanceDescFlowInstanceID := flownodeinstanceFields[0].Descriptor()
	// flownodeinstance.FlowInstanceIDValidator is a validator for the "flow_instance_id" field. It is called by the builders before save.
	flownodeinstance.FlowInstanceIDValidator = flownodeinstanceDescFlowInstanceID.Validators[0].(func(string) error)
	// flownodeinstanceDescSourceFlowNodeInstanceID is the schema descriptor for source_flow_node_instance_id field.
	flownodeinstanceDescSourceFlowNodeInstanceID := flownodeinstanceFields[1].Descriptor()
	// flownodeinstance.DefaultSourceFlowNodeInstanceID holds the default value on creation for the source_flow_node_instance_id field.
	flownodeinstance.DefaultSourceFlowNodeInstanceID = flownodeinstanceDescSourceFlowNodeInstanceID.Default.(string)
	// flownodeinstanceDescFlowInstanceDataID is the schema descriptor for flow_instance_data_id field.
	flownodeinstanceDescFlowInstanceDataID := flownodeinstanceFields[2].Descriptor()
	// flownodeinstance.DefaultFlowInstanceDataID holds the default value on creation for the flow_instance_data_id field.
	flownodeinstance.DefaultFlowInstanceDataID = flownodeinstanceDescFlowInstanceDataID.Default.(string)
	// flownodeinstanceDescNodeKey is the schema descriptor for node_key field.
	flownodeinstanceDescNodeKey := flownodeinstanceFields[3].Descriptor()
	// flownodeinstance.NodeKeyValidator is a validator for the "node_key" field. It is called by the builders before save.
	flownodeinstance.NodeKeyValidator = flownodeinstanceDescNodeKey.Validators[0].(func(string) error)
	// flownodeinstanceDescSourceNodeKey is the schema descriptor for source_node_key field.
	flownodeinstanceDescSourceNodeKey := flownodeinstanceFields[4].Descriptor()
	// flownodeinstance.DefaultSourceNodeKey holds the default value on creation for the source_node_key field.
	flownodeinstance.DefaultSourceNodeKey = flownodeinstanceDescSourceNodeKey.Default.(string)
	// flownodeinstanceDescStatus is the schema descriptor for status field.
	flownodeinstanceDescStatus := flownodeinstanceFields[5].Descriptor()
	// flownodeinstance.DefaultStatus holds the default value on creation for the status field.
	flownodeinstance.DefaultStatus = flownodeinstanceDescStatus.Default.(int8)
	// flownodeinstanceDescID is the schema descriptor for id field.
	flownodeinstanceDescID := flownodeinstanceMixinFields0[0].Descriptor()
	// flownodeinstance.DefaultID holds the default value on creation for the id field.
	flownodeinstance.DefaultID = flownodeinstanceDescID.Default.(func() string)
	// flownodeinstance.IDValidator is a validator for the "id" field. It is called by the builders before save.
	flownodeinstance.IDValidator = flownodeinstanceDescID.Validators[0].(func(string) error)
	flownodeinstancelogMixin := schema.FlowNodeInstanceLog{}.Mixin()
	flownodeinstancelogMixinFields0 := flownodeinstancelogMixin[0].Fields()
	_ = flownodeinstancelogMixinFields0
	flownodeinstancelogMixinFields1 := flownodeinstancelogMixin[1].Fields()
	_ = flownodeinstancelogMixinFields1
	flownodeinstancelogFields := schema.FlowNodeInstanceLog{}.Fields()
	_ = flownodeinstancelogFields
	// flownodeinstancelogDescCreatedAt is the schema descriptor for created_at field.
	flownodeinstancelogDescCreatedAt := flownodeinstancelogMixinFields1[0].Descriptor()
	// flownodeinstancelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	flownodeinstancelog.DefaultCreatedAt = flownodeinstancelogDescCreatedAt.Default.(func() int64)
	// flownodeinstancelogDescUpdatedAt is the schema descriptor for updated_at field.
	flownodeinstancelogDescUpdatedAt := flownodeinstancelogMixinFields1[1].Descriptor()
	// flownodeinstancelog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	flownodeinstancelog.DefaultUpdatedAt = flownodeinstancelogDescUpdatedAt.Default.(func() int64)
	// flownodeinstancelog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	flownodeinstancelog.UpdateDefaultUpdatedAt = flownodeinstancelogDescUpdatedAt.UpdateDefault.(func() int64)
	// flownodeinstancelogDescDeletedAt is the schema descriptor for deleted_at field.
	flownodeinstancelogDescDeletedAt := flownodeinstancelogMixinFields1[2].Descriptor()
	// flownodeinstancelog.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	flownodeinstancelog.DefaultDeletedAt = flownodeinstancelogDescDeletedAt.Default.(int64)
	// flownodeinstancelogDescFlowInstanceID is the schema descriptor for flow_instance_id field.
	flownodeinstancelogDescFlowInstanceID := flownodeinstancelogFields[0].Descriptor()
	// flownodeinstancelog.FlowInstanceIDValidator is a validator for the "flow_instance_id" field. It is called by the builders before save.
	flownodeinstancelog.FlowInstanceIDValidator = flownodeinstancelogDescFlowInstanceID.Validators[0].(func(string) error)
	// flownodeinstancelogDescFlowNodeInstanceID is the schema descriptor for flow_node_instance_id field.
	flownodeinstancelogDescFlowNodeInstanceID := flownodeinstancelogFields[1].Descriptor()
	// flownodeinstancelog.FlowNodeInstanceIDValidator is a validator for the "flow_node_instance_id" field. It is called by the builders before save.
	flownodeinstancelog.FlowNodeInstanceIDValidator = flownodeinstancelogDescFlowNodeInstanceID.Validators[0].(func(string) error)
	// flownodeinstancelogDescFlowInstanceDataID is the schema descriptor for flow_instance_data_id field.
	flownodeinstancelogDescFlowInstanceDataID := flownodeinstancelogFields[2].Descriptor()
	// flownodeinstancelog.DefaultFlowInstanceDataID holds the default value on creation for the flow_instance_data_id field.
	flownodeinstancelog.DefaultFlowInstanceDataID = flownodeinstancelogDescFlowInstanceDataID.Default.(string)
	// flownodeinstancelogDescNodeKey is the schema descriptor for node_key field.
	flownodeinstancelogDescNodeKey := flownodeinstancelogFields[3].Descriptor()
	// flownodeinstancelog.NodeKeyValidator is a validator for the "node_key" field. It is called by the builders before save.
	flownodeinstancelog.NodeKeyValidator = flownodeinstancelogDescNodeKey.Validators[0].(func(string) error)
	// flownodeinstancelogDescType is the schema descriptor for type field.
	flownodeinstancelogDescType := flownodeinstancelogFields[4].Descriptor()
	// flownodeinstancelog.DefaultType holds the default value on creation for the type field.
	flownodeinstancelog.DefaultType = flownodeinstancelogDescType.Default.(int8)
	// flownodeinstancelogDescStatus is the schema descriptor for status field.
	flownodeinstancelogDescStatus := flownodeinstancelogFields[5].Descriptor()
	// flownodeinstancelog.DefaultStatus holds the default value on creation for the status field.
	flownodeinstancelog.DefaultStatus = flownodeinstancelogDescStatus.Default.(int8)
	// flownodeinstancelogDescID is the schema descriptor for id field.
	flownodeinstancelogDescID := flownodeinstancelogMixinFields0[0].Descriptor()
	// flownodeinstancelog.DefaultID holds the default value on creation for the id field.
	flownodeinstancelog.DefaultID = flownodeinstancelogDescID.Default.(func() string)
	// flownodeinstancelog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	flownodeinstancelog.IDValidator = flownodeinstancelogDescID.Validators[0].(func(string) error)
}
